# Generated by Django 3.0.3 on 2020-02-04 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='Nombre de la empresa')),
                ('ciudad', models.CharField(max_length=50, verbose_name='Ciudad')),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido1', models.CharField(max_length=50, verbose_name='Primer apellido')),
                ('apellido2', models.CharField(max_length=50, verbose_name='Segundo apellido')),
                ('fecha_nac', models.DateField(auto_now_add=True, verbose_name='Fecha de nacimiento')),
                ('foto', models.ImageField(upload_to='fotos/', verbose_name='Foto')),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Empresa', verbose_name='Empresa donde trabaja')),
            ],
            options={
                'verbose_name': 'empleado',
                'verbose_name_plural': 'empleados',
                'ordering': ['-fecha_nac'],
            },
        ),
    ]
