# Generated by Django 3.0.3 on 2020-02-12 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(max_length=400, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion_dias', models.TextField(max_length=400, verbose_name='Horarios')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de finalización')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Precio del menú')),
            ],
            options={
                'verbose_name': 'tipo de menú',
                'verbose_name_plural': 'tipos de de menú',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(max_length=400, verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Precio del plato')),
                ('foto', models.ImageField(upload_to='fotos/platos/', verbose_name='Foto')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurante.Categoria', verbose_name='Categoría')),
                ('tipo_menu', models.ManyToManyField(to='restaurante.TipoMenu')),
            ],
            options={
                'verbose_name': 'plato',
                'verbose_name_plural': 'platos',
                'ordering': ['categoria', 'nombre'],
            },
        ),
    ]
