# Generated by Django 3.0.3 on 2020-02-19 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0002_auto_20200218_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='tipo_menu',
            field=models.ManyToManyField(related_name='get_menus', to='restaurante.TipoMenu', verbose_name='Menu'),
        ),
    ]
